mylist = [92,43,56,69,65]
# print(len(mylist))
ind = -1
# right = -1

def reversed(theList):
    theList.reverse()
    return theList

def sorted(theList):
    theList.sort()
    return theList

print(mylist)
print("Sorted:",sorted(mylist))
print("Reversed after sorting:",reversed(sorted(mylist)))

# reversing by slicing the list
for i in mylist:
    newlist = mylist[::-1]
print("Generated by slicing",newlist)

newlist = mylist
print("New list", newlist)

# getting mid item(s)
# for i in mylist:
#     ind += 1

# if ind % 2 == 0:
#     midn = int(ind/2)
#     print(mylist[midn])
# else:
#     print("Double mid numbers")
#     frt = int((ind - 1)/2)
#     lst = int((ind + 1)/2)
#     print(str(mylist[frt])+" and "+str(mylist[lst]))

# print(mylist)
# mylist[2:3]=[]
# print(mylist)
class geeksforgeeks:
    def __init__(self):
        self.geek = "Geeks for geeks"
    def print_geeks(self):
        print(self.geek)

obj = geeksforgeeks()
obj.print_geeks()

